#! /usr/bin/ruby
#
a=[
[1, "CR"],
[1, "CCR"],
[1, "TRIGGER"],
[1, "ASICCR"],
[1, "SR"],
[1, "SCR"],
[1, "TSSCR"],
[1, "TECR2"],
[1, "TEEVR"],
[1, "TECR1"],
[1, "FFRR"],
[1, "FFLR"],
[1, "VDEVR"],
[1, "VDCR1"],
[1, "VDCR2"],
[1, "VDCR3"],
[16, "ACVR"],
[16, "ACTR"],
[16, "DCVR"],
[16, "DCMR"],
[4, "CNTRLDVR"],
[4, "CNTENR"],
[4, "CNTRLDEVR"],
[4, "CNTVR"],
[6, "SQabEVR"],
[1, "RESERVED0"],
[1, "SQR"],
[4, "EXTOUTEVR"],
[3, "CIDCVR"],
[1, "CIDCMR"],
[8, "IMPL"],
[1, "SYNCFR"],
[1, "IDR"],
[1, "CCER"],
[1, "EXTINSELR"],
[1, "TESSEICR"],
[1, "EIBCR"],
[1, "TSEVR"],
[1, "AUXCR"],
[1, "TRACEIDR"],
[1, "RESERVED1"],
[1, "IDR2"],
[13, "RESERVED2"],
[1, "VMIDCVR"],
[47, "RESERVED3"],
[1, "OSLAR"],
[1, "OSLSR"],
[1, "OSSRR"],
[1, "RESERVED4"],
[1, "PDCR"],
[1, "PDSR"],
[762, "RESERVED5"],
[1, "ITCTRL"],
[39, "RESERVED6"],
[1, "CLAIMSET"],
[1, "CLAIMCLR"],
[2, "RESERVED7"],
[1, "LAR"],
[1, "LSR"],
[1, "AUTHSTATUS"],
[3, "RESERVED8"],
[1, "DEVID"],
[1, "DEVTYPE"],
[1, "PIDR4"],
[1, "PIDR5"],
[1, "PIDR6"],
[1, "PIDR7"],
[1, "PIDR0"],
[1, "PIDR1"],
[1, "PIDR2"],
[1, "PIDR3"],
[1, "CIDR0"],
[1, "CIDR1"],
[1, "CIDR2"],
[1, "CIDR3"]
]
loc = 0
a.each do |x|
  printf "%s at 16#%03x# range 0 .. 31;\n", x[1], loc
  loc += x[0] * 4
end
