with HAL;          use HAL;
package BLE_Status is

   type BLE_Status_Code is new UInt8;
   BLE_STATUS_OK                          : constant BLE_Status_Code := 16#00#;
   ERR_UNKNOWN_HCI_COMMAND                : constant BLE_Status_Code := 16#01#;
   ERR_UNKNOWN_CONN_IDENTIFIER            : constant BLE_Status_Code := 16#02#;
   ERR_AUTH_FAILURE                       : constant BLE_Status_Code := 16#05#;
   ERR_PIN_OR_KEY_MISSING                 : constant BLE_Status_Code := 16#06#;
   ERR_MEM_CAPACITY_EXCEEDED              : constant BLE_Status_Code := 16#07#;
   ERR_CONNECTION_TIMEOUT                 : constant BLE_Status_Code := 16#08#;
   ERR_COMMAND_DISALLOWED                 : constant BLE_Status_Code := 16#0C#;
   ERR_UNSUPPORTED_FEATURE                : constant BLE_Status_Code := 16#11#;
   ERR_INVALID_HCI_CMD_PARAMS             : constant BLE_Status_Code := 16#12#;
   ERR_RMT_USR_TERM_CONN                  : constant BLE_Status_Code := 16#13#;
   ERR_RMT_DEV_TERM_CONN_LOW_RESRCES      : constant BLE_Status_Code := 16#14#;
   ERR_RMT_DEV_TERM_CONN_POWER_OFF        : constant BLE_Status_Code := 16#15#;
   ERR_LOCAL_HOST_TERM_CONN               : constant BLE_Status_Code := 16#16#;
   ERR_UNSUPP_RMT_FEATURE                 : constant BLE_Status_Code := 16#1A#;
   ERR_INVALID_LMP_PARAM                  : constant BLE_Status_Code := 16#1E#;
   ERR_UNSPECIFIED_ERROR                  : constant BLE_Status_Code := 16#1F#;
   ERR_LL_RESP_TIMEOUT                    : constant BLE_Status_Code := 16#22#;
   ERR_LMP_PDU_NOT_ALLOWED                : constant BLE_Status_Code := 16#24#;
   ERR_INSTANT_PASSED                     : constant BLE_Status_Code := 16#28#;
   ERR_PAIR_UNIT_KEY_NOT_SUPP             : constant BLE_Status_Code := 16#29#;
   ERR_CONTROLLER_BUSY                    : constant BLE_Status_Code := 16#3A#;
   ERR_DIRECTED_ADV_TIMEOUT               : constant BLE_Status_Code := 16#3C#;
   ERR_CONN_END_WITH_MIC_FAILURE          : constant BLE_Status_Code := 16#3D#;
   ERR_CONN_FAILED_TO_ESTABLISH           : constant BLE_Status_Code := 16#3E#;
   BLE_STATUS_FAILED                      : constant BLE_Status_Code := 16#41#;
   BLE_STATUS_INVALID_PARAMS              : constant BLE_Status_Code := 16#42#;
   BLE_STATUS_NOT_ALLOWED                 : constant BLE_Status_Code := 16#46#;
   BLE_STATUS_ERROR                       : constant BLE_Status_Code := 16#47#;
   BLE_STATUS_ADDR_NOT_RESOLVED           : constant BLE_Status_Code := 16#48#;
   FLASH_READ_FAILED                      : constant BLE_Status_Code := 16#49#;
   FLASH_WRITE_FAILED                     : constant BLE_Status_Code := 16#4A#;
   FLASH_ERASE_FAILED                     : constant BLE_Status_Code := 16#4B#;
   BLE_STATUS_INVALID_CID                 : constant BLE_Status_Code := 16#50#;
   TIMER_NOT_VALID_LAYER                  : constant BLE_Status_Code := 16#54#;
   TIMER_INSUFFICIENT_RESOURCES           : constant BLE_Status_Code := 16#55#;
   BLE_STATUS_CSRK_NOT_FOUND              : constant BLE_Status_Code := 16#5A#;
   BLE_STATUS_IRK_NOT_FOUND               : constant BLE_Status_Code := 16#5B#;
   BLE_STATUS_DEV_NOT_FOUND_IN_DB         : constant BLE_Status_Code := 16#5C#;
   BLE_STATUS_SEC_DB_FULL                 : constant BLE_Status_Code := 16#5D#;
   BLE_STATUS_DEV_NOT_BONDED              : constant BLE_Status_Code := 16#5E#;
   BLE_STATUS_DEV_IN_BLACKLIST            : constant BLE_Status_Code := 16#5F#;
   BLE_STATUS_INVALID_HANDLE              : constant BLE_Status_Code := 16#60#;
   BLE_STATUS_INVALID_PARAMETER           : constant BLE_Status_Code := 16#61#;
   BLE_STATUS_OUT_OF_HANDLE               : constant BLE_Status_Code := 16#62#;
   BLE_STATUS_INVALID_OPERATION           : constant BLE_Status_Code := 16#63#;
   BLE_STATUS_INSUFFICIENT_RESOURCES      : constant BLE_Status_Code := 16#64#;
   BLE_INSUFFICIENT_ENC_KEYSIZE           : constant BLE_Status_Code := 16#65#;
   BLE_STATUS_CHARAC_ALREADY_EXISTS       : constant BLE_Status_Code := 16#66#;
   BLE_STATUS_NO_VALID_SLOT               : constant BLE_Status_Code := 16#82#;
   BLE_STATUS_SCAN_WINDOW_SHORT           : constant BLE_Status_Code := 16#83#;
   BLE_STATUS_NEW_INTERVAL_FAILED         : constant BLE_Status_Code := 16#84#;
   BLE_STATUS_INTERVAL_TOO_LARGE          : constant BLE_Status_Code := 16#85#;
   BLE_STATUS_LENGTH_FAILED               : constant BLE_Status_Code := 16#86#;
   BLE_STATUS_PROFILE_ALREADY_INITIALIZED : constant BLE_Status_Code := 16#F0#;
   BLE_STATUS_NULL_PARAM                  : constant BLE_Status_Code := 16#F1#;
   BLE_STATUS_TIMEOUT                     : constant BLE_Status_Code := 16#FF#;

end BLE_Status;
